### PR TITLE
Add support to start karate in Repository directory with specified Path

### PR DESCRIPTION
**Pull request by ThumNet**
## Pull request description 
We are using karate for our tests and have multiple feature files in in specific directory. This directory also contains the `karate-config.js` with the current version it was very hard to get karate working for our process. That's why I created this PR to be able to start the karate executable from the Repository.Path.

## Checklist (choose whats happened)

- [ ] breaking change! (describe)
- [x] tested locally
- [ ] tested on cluster
- [ ] added new dependencies
- [ ] updated the docs
- [x] added a test

## Breaking changes
none

### CODE REVIEW

**Comment by lreimer** [comment]
Thanks for this improvement @ThumNet

**Comment by ThumNet** [comment]
Thank you for merging the code in :+1: 

@lreimer  What is the process to get the new version available?
Because I don't see a new version on docker hub.

**Comment by lreimer** [comment]
Good question. No real process yet.
I will an an action later today to release the latest image via Github packages.

**Comment by ThumNet** [comment]
@lreimer I believe the action is already [defined](https://github.com/lreimer/testkube-executor-karate/blob/main/.github/workflows/docker-build.yaml) and it looks like it is configured to run on a `tag` push.

Sorry for harassing you like this, but we are looking forward to the new functionality :)

**Comment by lreimer** [comment]
All good. Published to Docker Hub and Github Packages now. Have fun with the new functionality.

**Pull request merged**
